name: sh Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-20 xxd gcc-multilib libbpf-dev
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 100
      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
      - name: Upload xdp_loader artifact
        uses: actions/upload-artifact@v4
        with:
          name: xdp_loader
          path: ./xdp_loader
